version: 2
jobs:
  build:
    docker:
      - image: python:3.4-jessie
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install -y libcv-dev libopencv-photo-dev libopencv-contrib-dev
      - run: pip3 install pipenv
      - run: pipenv install --dev
      - run: pipenv run python setup.py test
      - run: pipenv run pytest --flake8 sb_vision tests
