version: 2
jobs:
  build:
    docker:
      - image: python:3.4-jessie
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install -y libcv-dev libopencv-photo-dev libopencv-contrib-dev
      - run: python3 -m venv venv
      - run: venv/bin/pip install .
      - run: venv/bin/pip install pytest
      - run: venv/bin/pip install -r script/linting/requirements.txt
      - run: venv/bin/py.test tests
      - run:
          command: script/linting/lint
          environment:
            FLAKE8: venv/bin/flake8
